### ISSUE TITLE
Documentation code snippets incompatible with Elm 0.18.0 in version 1.10.1

### ISSUE THREAD

**Issue by inactivist** [tomjkidd/elm-multiway-tree-zipper#16]
The `&>` infix operator as defined doesn't work as expected because `Maybe.andThen` params are reversed in 0.18.0.  

(Haven't verified this.  Expectation based on experience upgrading this module to Elm 0.18.0.)

**Comment by tomjkidd** [comment]
I will have to devote some time to this in the coming days, the 0.18.0 upgrade is still new to me and I will have to look around for if there is a new standard way of dealing with chaining.

**Comment by tomjkidd** [comment]
Turns out this was really easy to fix, just have to use `(&>) = flip Maybe.andThen`

**Comment by inactivist** [comment]
Thanks for investigating and fixing this - I admit I was unaware of `flip` (new to Elm -- though it's pretty obvious now that I think about it).
